- package.json
- src/App.css
- src/pages/shipments/index.js
> Changed button and shpiments

- package.json
- src/components/Dashboard.js
- src/components/SignIn.js
- src/constants/constants.js
- src/pages/customers/index.js
- src/pages/home/index.js
- src/pages/products/index.js
- src/pages/providers/index.js
- src/pages/receipts/index.js
- src/pages/shipments/index.js
- src/pages/staff/index.js
Removed some of they keys from different pages. Can be easily re-added by removing comments from the constants.js file. 
Also added custom filtering to several pages, easy to add to others.
> Custom fitler

- src/pages/reports/index.js
> added custom filtering to reports

- src/components/form/ProductItems.js
> This is a fix for add new shipments style

- src/components/SignUp.js
- src/components/form/ProviderInfo.js
- src/components/form/types/CustomerForm.js
- src/components/form/types/ProductForm.js
- src/components/form/types/ProviderForm.js
- src/components/form/types/StaffForm.js
- src/constants/constants.js
- src/firebase/db.js
- src/pages/staff/index.js
Added staff page and messed around with some styles across all forms
> Staff form

- src/components/form/types/ProductForm.js
- src/pages/receipts/index.js
- src/pages/reports/index.js
- src/pages/shipments/index.js
cleaned up column headers in receipts and shipments and reports
> cleaned up some more column names

- src/components/form/ProductItems.js
- src/pages/products/index.js
- src/pages/receipts/index.js
- src/pages/reports/index.js
- src/pages/shipments/index.js
> Sorting2020

- src/components/form/CustomerAutoComplete.js
- src/components/form/ProductAutoComplete.js
- src/components/form/ProviderAutoComplete.js
- src/components/form/types/CustomerForm.js
- src/components/form/types/ProductForm.js
- src/components/form/types/ProviderForm.js
- src/components/form/types/ReceiptForm.js
- src/components/form/types/ShipmentForm.js
- src/firebase/db.js
- src/pages/receipts/index.js
makes receipts editable and deletable, cleans up some areas of the codebase, and adds some error handling where I thought it would be smart to have
> Edit receipts + misc changes

- src/components/TableDropdown.js
- src/components/form/Footer.js
- src/components/form/ProductItems.js
- src/components/form/types/CustomerForm.js
- src/components/form/types/ProductForm.js
- src/components/form/types/ProviderForm.js
- src/components/form/types/ReceiptForm.js
- src/components/form/types/ShipmentForm.js
- src/components/form/types/StaffForm.js
- src/pages/customers/index.js
- src/pages/products/index.js
- src/pages/providers/index.js
- src/pages/receipts/index.js
- src/pages/shipments/index.js
- src/pages/staff/index.js
does a lot of things, fixes css, adjusts variables names, usability for delete button, console warnings, and ultimately adds a loading animation for form submit, with the exception of the staff form
> Load submit

- .eslintrc.json
- .hound.yml
- package.json
> add eslint config to repo and HoundCI config

- .hound.yml
this way people can't merge unless they fix their PRs
> make hound fail PRs if they violate rules

- .eslintrc.json
makes 3 minor changes to how the react rules work to make eslint a little less strict
> make eslint a little less strict

- src/components/App.js
- src/components/Dashboard.js
- src/components/SignUp.js
- src/components/withAuthorization.js
- src/constants/roles.js
- src/firebase/db.js
- src/pages/customers/index.js
- src/pages/help/index.js
- src/pages/home/index.js
- src/pages/products/index.js
- src/pages/providers/index.js
- src/pages/receipts/index.js
- src/pages/reports/index.js
- src/pages/shipments/index.js
- src/pages/staff/index.js
fixes #8 issues and is part of MVP. Allows only people with designated as admin to access staff and products page, and as oppose to the other PR it doesn't do styling changes
> Permissions pure

- .firebaserc
- .gitignore
- firebase.json
- package.json
Adds the necessary files created using the Firebase CLI tool to deploy the project.
> add firebase hosting & deploying code

- .eslintrc.json
because I like using ++ in my for loops
> change eslint to allow for ForLoopAfterThoughts

- .eslintrc.json
hopefully this'll make Hound happy
> Eslint prettier fix

- src/components/Dashboard.js
adds new layout to make app better looking and easier to use, mainly by using a vertical sider for navigation rather than a horizontal menu
> revamp layout of application to add sider for navigation

- src/components/App.js
- src/components/SignUp.js
this is useful while the backend is still in need of debugging, also I updated it to make roles work with it
> make signup page accessible again for debugging purposes

- src/components/form/ProductItems.js
Takes the unit weight and case lot and trys to autocalculate the values if the user inputs anything into the case lots or unit weight fields. Still allows user to hardcode total weight if needed
> make total weight in productItems component autocalculate

- src/components/FundsSourceDropdownMenu.js
small fix, easy fix, just how I like em
> fix funding source dropdown bug

- src/components/form/ProductAutoComplete.js
- src/components/form/ProductItems.js
- src/firebase/db.js
> make products auto-fill in unit weight on product select

- src/constants/constants.js
- src/pages/reports/utils.js
- src/utils/misc.js
> Actually implement Current Customers and Current Providers Report

- src/constants/constants.js
- src/pages/customers/index.js
- src/pages/products/index.js
- src/pages/providers/index.js
- src/pages/receipts/index.js
- src/pages/reports/index.js
- src/pages/reports/utils.js
- src/pages/shipments/index.js
- src/utils/misc.js
> clean up, fix, and add new column filtering features

- src/pages/reports/index.js
closes #187
had to pull a trick on the download component to get it to work but I documented why i did it in a verbose bit of documentation
> make reports csv download reflect internal state of react-table

- src/components/form/Footer.js
- src/components/form/types/ReceiptForm.js
- src/components/form/types/ShipmentForm.js
- src/components/form/types/pdfUtils.js
- src/firebase/db.js
- src/utils/misc.js
fixes #179
closes #90 
also does some much needed house keeping related to the code that generates pdfs
> add printable receipts, fix invoices, and consolidate pdf-related code

- src/components/form/types/ProductForm.js
- src/components/form/types/ProviderForm.js
- src/components/form/types/ReceiptForm.js
- src/components/form/types/ShipmentForm.js
- src/components/form/types/pdfUtils.js
- src/firebase/db.js
- src/pages/customers/index.js
- src/pages/home/index.js
- src/pages/products/index.js
- src/pages/providers/index.js
- src/pages/receipts/index.js
- src/pages/shipments/index.js
- src/pages/staff/index.js
- src/pages/styles.js
- src/utils/misc.js
will cause breaking changes if you aren't on the bmac-warehouse-dev db instance
> Posix date updates + misc updates

- package.json
- src/pages/reports/index.js
also do some nice things like make the file names of the report correspond to the type of report you are currently using
> update buggy csv package and refactor corresponding code

- src/components/form/Footer.js
- src/components/form/ProductAutoComplete.js
- src/components/form/ProductItems.js
- src/components/form/types/ProductForm.js
- src/components/form/types/ReceiptForm.js
- src/components/form/types/ShipmentForm.js
- src/components/form/types/pdfUtils.js
- src/constants/constants.js
- src/pages/receipts/EditableReceiptTable.js
- src/pages/receipts/index.js
- src/pages/reports/index.js
- src/pages/reports/utils.js
- src/pages/shipments/EditableShipmentTable.js
- src/pages/shipments/index.js
adds new material number feature to app, along the way I fixed a few things that were bugging me along the way
> Material number feature

- src/components/CustomDatePicker.jsx
- src/components/form/Footer.js
- src/components/form/ProductItems.js
- src/components/form/types/ProductForm.js
- src/components/form/types/ProviderForm.js
- src/components/form/types/ReceiptForm.js
- src/components/form/types/ShipmentForm.js
- src/constants/constants.js
- src/pages/receipts/EditableReceiptTable.js
- src/pages/receipts/index.js
- src/pages/reports/index.js
- src/pages/shipments/EditableShipmentTable.js
- src/pages/shipments/index.js
- src/utils/misc.js
lots of little things I've been meaning to get to, also found some bugs along the way and squashed them
> Misc updates

- src/components/App.js
- src/components/Dashboard.js
- src/constants/constants.js
- src/pages/home/index.js
- src/pages/shipments/EditableShipmentTable.js
- src/pages/shipments/index.js
few minor things before soft launch tomorrow
> Soft launch

- firebase.json
- functions/.eslintrc.json
- functions/.gitignore
- functions/index.js
- functions/package.json
- package.json
- src/components/form/Footer.js
- src/components/form/ProductItems.js
- src/components/form/ProviderAutoComplete.js
- src/components/form/types/CustomerForm.js
- src/components/form/types/FundingSourceForm.js
- src/components/form/types/PasswordFields.jsx
- src/components/form/types/ProductForm.js
- src/components/form/types/ProviderForm.js
- src/components/form/types/ReceiptForm.js
- src/components/form/types/ShipmentForm.js
- src/components/form/types/StaffForm.js
- src/components/form/types/pdfUtils.js
- src/components/form/types/styles.js
- src/constants/constants.js
- src/firebase/auth.js
- src/firebase/db.js
- src/firebase/firebase.js
- src/pages/staff/index.js
- src/utils/misc.js
big PR with lots of different features, bug fixes, and minor changes
> Various changes
